### ISSUE TITLE
build dependencies

### ISSUE THREAD

**Issue by gedw99** [pierrre/imageserver#6]
do you have a script to install the graphicsmagick ?
I could not see one in the travis file, so wondering how to have an automated setup

**Comment by gedw99** [comment]
ah. i see it in the travis file

```

addons:
  apt:
    packages:
      - graphicsmagick

```

I was looking for a way to do it on my OSX locally, in an automated way.
If you have any tips :)
